# @package suite
defaults:
  - _self_
  - task: xarm_env

suite: xarm_env
name: "xarm_env"

# task settings
frame_stack: 1
action_repeat: 1
discount: 0.99
hidden_dim: 256
action_type: continuous

# train settings
num_train_steps: 500000
log_every_steps: 100
save_every_steps: 500
history: false
history_len: 10
# history_len:
#   default: 1
#   sensor: 15
num_train_steps_per_task: 20000 #2500 #5000

# eval
eval_every_steps: 200000 #20000 #5000
num_eval_episodes: 5
# eval_history_len: 5
eval_history_len:
  default: 1
  sensor: 10

# data loading
action_after_steps: 1 #8

# obs_keys
pixel_keys: ["pixels1", "pixels2", "pixels51",  "pixels52"]
#aux_keys: ["sensor0", "sensor1"]
aux_keys: ['proprioceptive']
feature_key: "proprioceptive"
sensor_params:
  subtract_sensor_baseline: true
  use_sensor_diffs: false
  separate_sensors: false

# snapshot
save_snapshot: true

task_make_fn:
  _target_: suite.xarm_env.make
  # suite: ${suite.task.suite}
  # scenes: ${suite.task.scenes}
  # tasks: ${suite.task.tasks}
  frame_stack: ${suite.frame_stack}
  action_repeat: ${suite.action_repeat}
  seed: ${seed}
  height: 128
  width: 128
  max_episode_len: ??? # to be specified later
  max_state_dim: ??? # to be specified later
  use_egocentric: true
  use_fisheye: true
  task_description: "just training"
  pixel_keys: ${suite.pixel_keys}
  aux_keys: ${suite.aux_keys}
  sensor_params: ${suite.sensor_params}
  eval: ${eval} # eval true mean use robot
